### ISSUE TITLE
Update to the latest 7.2.1.1 version

### ISSUE THREAD

**Issue by alex-kolb** [PushkinStudio/PsIronSource#29]
Hi,

Do you plan to update your plugin to the latest IronSource SDK 7.2.1.1 ? Thanks for answer

**Comment by Antonrr** [comment]
Hello,

Yes, we will eventually update the plugin to the latest SDK version.

Regards,
Anton

**Comment by alex-kolb** [comment]
Great news! Maybe you have any approximate dates ? Thank you

**Comment by Antonrr** [comment]
Sometime in April if everything is OK.

**Comment by alex-kolb** [comment]
Hi, do you have any updates on this issue ?

**Comment by Antonrr** [comment]
Hello! I've updated the plugin to version 7.2.1.
